-- GudanBridge Care - Script de Modelagem de Dados (DER) e Automação
-- Banco: Oracle
-- Este script cria as tabelas, sequências e procedures principais.

--------------------------------------------------------
-- TABELAS
--------------------------------------------------------

CREATE TABLE COLABORADOR (
  ID_COLABORADOR     NUMBER(10)      PRIMARY KEY,
  NOME               VARCHAR2(100)   NOT NULL,
  EMAIL_CORPORATIVO  VARCHAR2(150)   NOT NULL UNIQUE,
  DEPARTAMENTO       VARCHAR2(80),
  CARGO              VARCHAR2(80),
  DATA_CADASTRO      DATE            DEFAULT SYSDATE,
  ATIVO              CHAR(1)         DEFAULT 'S' CHECK (ATIVO IN ('S','N'))
);

CREATE TABLE CHECKIN_EMOCIONAL (
  ID_CHECKIN     NUMBER(10)    PRIMARY KEY,
  ID_COLABORADOR NUMBER(10)    NOT NULL,
  DATA_HORA      TIMESTAMP     DEFAULT SYSTIMESTAMP,
  HUMOR          NUMBER(2)     CHECK (HUMOR BETWEEN 1 AND 5),
  ENERGIA        NUMBER(2)     CHECK (ENERGIA BETWEEN 1 AND 10),
  CARGA_TRABALHO VARCHAR2(20)  CHECK (CARGA_TRABALHO IN ('BAIXA','EQUILIBRADA','ALTA')),
  COMENTARIO     VARCHAR2(500),
  CONSTRAINT FK_CHECKIN_COLAB FOREIGN KEY (ID_COLABORADOR)
    REFERENCES COLABORADOR (ID_COLABORADOR)
);

CREATE TABLE HABITO (
  ID_HABITO         NUMBER(10)    PRIMARY KEY,
  NOME              VARCHAR2(100) NOT NULL,
  TIPO              VARCHAR2(30),
  DESCRICAO         VARCHAR2(500),
  NIVEL_INTENSIDADE NUMBER(1)    CHECK (NIVEL_INTENSIDADE BETWEEN 1 AND 3),
  ATIVO             CHAR(1)      DEFAULT 'S' CHECK (ATIVO IN ('S','N'))
);

CREATE TABLE PLANO_HABITO (
  ID_PLANO       NUMBER(10)    PRIMARY KEY,
  ID_COLABORADOR NUMBER(10)    NOT NULL,
  ID_HABITO      NUMBER(10)    NOT NULL,
  FREQUENCIA     VARCHAR2(20)  CHECK (FREQUENCIA IN ('DIARIO','3X_SEMANA','SEMANAL')),
  DATA_INICIO    DATE          DEFAULT TRUNC(SYSDATE),
  DATA_FIM       DATE,
  STATUS         VARCHAR2(20)  DEFAULT 'ATIVO'
                 CHECK (STATUS IN ('ATIVO','CONCLUIDO','PAUSADO')),
  CONSTRAINT FK_PLANO_COLAB FOREIGN KEY (ID_COLABORADOR)
    REFERENCES COLABORADOR (ID_COLABORADOR),
  CONSTRAINT FK_PLANO_HABITO FOREIGN KEY (ID_HABITO)
    REFERENCES HABITO (ID_HABITO)
);

CREATE TABLE EXECUCAO_HABITO (
  ID_EXECUCAO   NUMBER(10)    PRIMARY KEY,
  ID_PLANO      NUMBER(10)    NOT NULL,
  DATA_EXECUCAO DATE          DEFAULT TRUNC(SYSDATE),
  VALOR         NUMBER(5,2),
  COMENTARIO    VARCHAR2(300),
  CONSTRAINT FK_EXEC_PLANO FOREIGN KEY (ID_PLANO)
    REFERENCES PLANO_HABITO (ID_PLANO)
);

CREATE TABLE META_DESENVOLVIMENTO (
  ID_META        NUMBER(10)    PRIMARY KEY,
  ID_COLABORADOR NUMBER(10)    NOT NULL,
  CATEGORIA      VARCHAR2(20)  CHECK (CATEGORIA IN ('PESSOAL','PROFISSIONAL')),
  TITULO         VARCHAR2(120) NOT NULL,
  DESCRICAO      VARCHAR2(500),
  DATA_INICIO    DATE          DEFAULT TRUNC(SYSDATE),
  DATA_PRAZO     DATE,
  STATUS         VARCHAR2(20)  DEFAULT 'EM_ANDAMENTO'
                 CHECK (STATUS IN ('EM_ANDAMENTO','CONCLUIDA','PAUSADA')),
  CONSTRAINT FK_META_COLAB FOREIGN KEY (ID_COLABORADOR)
    REFERENCES COLABORADOR (ID_COLABORADOR)
);

CREATE TABLE ACAO_DESENVOLVIMENTO (
  ID_ACAO        NUMBER(10)    PRIMARY KEY,
  ID_META        NUMBER(10)    NOT NULL,
  DESCRICAO      VARCHAR2(400) NOT NULL,
  TIPO           VARCHAR2(30),
  DATA_PREVISTA  DATE,
  DATA_REALIZADA DATE,
  STATUS         VARCHAR2(20)  DEFAULT 'PENDENTE'
                 CHECK (STATUS IN ('PENDENTE','REALIZADA','ATRASADA')),
  CONSTRAINT FK_ACAO_META FOREIGN KEY (ID_META)
    REFERENCES META_DESENVOLVIMENTO (ID_META)
);

CREATE TABLE USO_APP_LOG (
  ID_LOG          NUMBER(10)    PRIMARY KEY,
  ID_COLABORADOR  NUMBER(10)    NOT NULL,
  DATA_HORA       TIMESTAMP     DEFAULT SYSTIMESTAMP,
  FUNCIONALIDADE  VARCHAR2(50),
  DURACAO_SEGUNDOS NUMBER(10),
  CONSTRAINT FK_LOG_COLAB FOREIGN KEY (ID_COLABORADOR)
    REFERENCES COLABORADOR (ID_COLABORADOR)
);

CREATE TABLE METRICA_DIARIA_COLAB (
  ID_METRICA              NUMBER(10)  PRIMARY KEY,
  ID_COLABORADOR          NUMBER(10)  NOT NULL,
  DATA_REF                DATE        NOT NULL,
  HUMOR_MEDIO             NUMBER(4,2),
  ENERGIA_MEDIA           NUMBER(4,2),
  QTD_CHECKINS            NUMBER(5),
  QTD_HABITOS_EXECUTADOS  NUMBER(5),
  CONSTRAINT UQ_METRICA_COLAB_DIA UNIQUE (ID_COLABORADOR, DATA_REF),
  CONSTRAINT FK_METRICA_COLAB FOREIGN KEY (ID_COLABORADOR)
    REFERENCES COLABORADOR (ID_COLABORADOR)
);

CREATE TABLE ALERTA_BEM_ESTAR (
  ID_ALERTA      NUMBER(10)   PRIMARY KEY,
  ID_COLABORADOR NUMBER(10)   NOT NULL,
  DATA_REF       DATE         NOT NULL,
  TIPO_ALERTA    VARCHAR2(40),
  DESCRICAO      VARCHAR2(500),
  NIVEL          NUMBER(1)    CHECK (NIVEL BETWEEN 1 AND 3),
  TRATADO        CHAR(1)      DEFAULT 'N' CHECK (TRATADO IN ('S','N')),
  CONSTRAINT FK_ALERTA_COLAB FOREIGN KEY (ID_COLABORADOR)
    REFERENCES COLABORADOR (ID_COLABORADOR)
);

--------------------------------------------------------
-- SEQUENCES
--------------------------------------------------------

CREATE SEQUENCE SEQ_COLABORADOR START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CHECKIN START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_HABITO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PLANO_HABITO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EXECUCAO_HABITO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_META_DESENV START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ACAO_DESENV START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_USO_LOG START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_METRICA_DIARIA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ALERTA START WITH 1 INCREMENT BY 1;

--------------------------------------------------------
-- PROCEDURES DE AUTOMAÇÃO
--------------------------------------------------------

-- 1) Registro de uso do app
CREATE OR REPLACE PROCEDURE REGISTRAR_USO_APP (
  p_id_colaborador   IN USO_APP_LOG.ID_COLABORADOR%TYPE,
  p_funcionalidade   IN USO_APP_LOG.FUNCIONALIDADE%TYPE,
  p_duracao_segundos IN USO_APP_LOG.DURACAO_SEGUNDOS%TYPE DEFAULT NULL
) AS
BEGIN
  INSERT INTO USO_APP_LOG (
    ID_LOG,
    ID_COLABORADOR,
    DATA_HORA,
    FUNCIONALIDADE,
    DURACAO_SEGUNDOS
  ) VALUES (
    SEQ_USO_LOG.NEXTVAL,
    p_id_colaborador,
    SYSTIMESTAMP,
    p_funcionalidade,
    p_duracao_segundos
  );

  COMMIT;
END;
/
SHOW ERRORS;


-- 2) Cálculo de métricas diárias de bem-estar
CREATE OR REPLACE PROCEDURE CALCULAR_METRICAS_DIARIAS (
  p_data_ref IN DATE
) AS
BEGIN
  DELETE FROM METRICA_DIARIA_COLAB
   WHERE DATA_REF = TRUNC(p_data_ref);

  INSERT INTO METRICA_DIARIA_COLAB (
    ID_METRICA,
    ID_COLABORADOR,
    DATA_REF,
    HUMOR_MEDIO,
    ENERGIA_MEDIA,
    QTD_CHECKINS,
    QTD_HABITOS_EXECUTADOS
  )
  SELECT
    SEQ_METRICA_DIARIA.NEXTVAL,
    c.ID_COLABORADOR,
    TRUNC(p_data_ref) AS DATA_REF,
    AVG(ch.HUMOR) AS HUMOR_MEDIO,
    AVG(ch.ENERGIA) AS ENERGIA_MEDIA,
    COUNT(ch.ID_CHECKIN) AS QTD_CHECKINS,
    (
      SELECT COUNT(eh.ID_EXECUCAO)
      FROM EXECUCAO_HABITO eh
      JOIN PLANO_HABITO ph
        ON ph.ID_PLANO = eh.ID_PLANO
     WHERE ph.ID_COLABORADOR = c.ID_COLABORADOR
       AND TRUNC(eh.DATA_EXECUCAO) = TRUNC(p_data_ref)
    ) AS QTD_HABITOS_EXECUTADOS
  FROM COLABORADOR c
  LEFT JOIN CHECKIN_EMOCIONAL ch
    ON ch.ID_COLABORADOR = c.ID_COLABORADOR
   AND TRUNC(ch.DATA_HORA) = TRUNC(p_data_ref)
  GROUP BY c.ID_COLABORADOR;

  COMMIT;
END;
/
SHOW ERRORS;


-- 3) Geração de alertas de bem-estar
CREATE OR REPLACE PROCEDURE GERAR_ALERTAS_BEM_ESTAR (
  p_data_ref IN DATE
) AS
BEGIN
  -- Alerta de humor baixo
  INSERT INTO ALERTA_BEM_ESTAR (
    ID_ALERTA,
    ID_COLABORADOR,
    DATA_REF,
    TIPO_ALERTA,
    DESCRICAO,
    NIVEL,
    TRATADO
  )
  SELECT
    SEQ_ALERTA.NEXTVAL,
    m.ID_COLABORADOR,
    m.DATA_REF,
    'BAIXO_HUMOR' AS TIPO_ALERTA,
    'Humor médio abaixo de 4 no dia ' || TO_CHAR(m.DATA_REF, 'DD/MM/YYYY'),
    3 AS NIVEL,
    'N' AS TRATADO
  FROM METRICA_DIARIA_COLAB m
  WHERE m.DATA_REF = TRUNC(p_data_ref)
    AND m.HUMOR_MEDIO < 4
    AND m.QTD_CHECKINS >= 2;

  -- Alerta de baixa adesão a hábitos
  INSERT INTO ALERTA_BEM_ESTAR (
    ID_ALERTA,
    ID_COLABORADOR,
    DATA_REF,
    TIPO_ALERTA,
    DESCRICAO,
    NIVEL,
    TRATADO
  )
  SELECT
    SEQ_ALERTA.NEXTVAL,
    m.ID_COLABORADOR,
    m.DATA_REF,
    'BAIXA_ADERENCIA_HABITOS',
    'Baixa execução de micro-hábitos no dia ' || TO_CHAR(m.DATA_REF, 'DD/MM/YYYY'),
    2 AS NIVEL,
    'N' AS TRATADO
  FROM METRICA_DIARIA_COLAB m
  WHERE m.DATA_REF = TRUNC(p_data_ref)
    AND NVL(m.QTD_HABITOS_EXECUTADOS, 0) = 0;

  COMMIT;
END;
/
SHOW ERRORS;

